### PR TITLE
fix pom

### PR DESCRIPTION
**Pull request by wsdjeg**

### CODE REVIEW

**Comment by alorma** [comment]
I will update the libs later today

**Comment by wsdjeg** [comment]
i change the lib just depandence you gradle.build so i think you has no need to change,but it base on your mind,i will follow you

**Comment by alorma** [comment]
I will update, so it has the correct pom in bintray too

**Comment by wsdjeg** [comment]
but this project need the local android-sdk repository which is build with https://github.com/simpligility/maven-android-sdk-deployer
,google does not support the online repository for android-sdk

**Pull request merged**
